require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rswag-specs: .rubocop_rspec_alias_config.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable

# Styles

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

# Metrics

Metrics/ParameterLists:
  Enabled: true
  Exclude:
    - "contexts/shared/infrastructure/error.rb"

Metrics/MethodLength:
  Enabled: true
  CountAsOne: ["array", "heredoc", "method_call"]

Metrics/AbcSize:
  Enabled: true
  CountRepeatedAttributes: false

# Rails

Rails/DynamicFindBy:
  Enabled: true
  AllowedReceivers:
    - repository

Rails/SkipsModelValidations:
  Enabled: true
  AllowedMethods:
    - increment!

# Tests

RSpec/NestedGroups:
  Enabled: true
  Exclude:
    - "spec/apps/**/*_request_spec.rb"
    - "spec/contexts/**/*_use_case_spec.rb"
    - "spec/contexts/**/*_repository_spec.rb"

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - "spec/contexts/**/*_use_case_spec.rb"
    - "spec/contexts/**/*_repository_spec.rb"
    - "spec/apps/**/*_request_spec.rb"

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/VariableName:
  Enabled: true
  Exclude:
    - "spec/apps/**/*_request_spec.rb"

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - "spec/apps/**/*_request_spec.rb"
