require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rswag-specs: .rubocop_rspec_alias_config.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable

# Styles

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# Tests

RSpec/NestedGroups:
  Enabled: true
  Exclude:
    - "spec/apps/**/*_request_spec.rb"
