require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rswag-specs: .rubocop_rspec_alias_config.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable

# Styles

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

# Metrics

Metrics/ParameterLists:
  Enabled: true
  Exclude:
    - "app/errors/error.rb"

Metrics/MethodLength:
  Enabled: true
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Exclude:
    - "app/controllers/api/v1/safebox_items_controller.rb"

Metrics/AbcSize:
  Enabled: true
  CountRepeatedAttributes: false
  Exclude:
    - "app/controllers/api/v1/safebox_items_controller.rb"

# Performance

Performance/Sum:
  Enabled: true
  Exclude:
    - "app/validators/parametizable_query_validator.rb"

# Rails

Rails/DynamicFindBy:
  Enabled: true
  AllowedReceivers:
    - repository

Rails/SkipsModelValidations:
  Enabled: true
  AllowedMethods:
    - increment!

# Tests

RSpec/NestedGroups:
  Enabled: true
  Exclude:
    - "spec/requests/**/*_request_spec.rb"

RSpec/ExampleLength:
  Enabled: true
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Exclude:
    - "spec/requests/**/*_request_spec.rb"

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/VariableName:
  Enabled: true
  Exclude:
    - "spec/requests/**/*_request_spec.rb"

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - "spec/requests/**/*_request_spec.rb"

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Exclude:
    - "spec/requests/**/*_request_spec.rb"

RSpec/Rails/InferredSpecType:
  Enabled: false
