version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret

  app:
    image: challenge-be-safebox-api-rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/app
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  postgres-data:
