version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: challenge-be-safebox-api-rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - .:/usr/app
    depends_on:
      - db

volumes:
  postgres-data:
