# syntax = docker/dockerfile:1

FROM ruby:3.3.0

WORKDIR /usr/app

COPY Gemfile* .ruby-version ./

RUN apt-get update -qq && apt-get install -y postgresql-client
RUN bundle install

COPY . .

ENTRYPOINT ["./bin/docker-entrypoint"]

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
