openapi: 3.0.0

info:
  description: |
    SafeIsh API - The most secure safebox
  version: 1.0.0
  title: SafeIsh API

paths:
  /safeboxes:
    post:
      summary: Creates a new safebox
      operationId: createSafebox
      description: |
        Creates a new safebox based on a UUID, a non-empty name and a password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  description: Safebox ID
                  type: string
                  format: uuid
                name:
                  description: Safebox Name
                  type: string
                password:
                  description: Safebox Password
                  type: string
              required:
                - id
                - name
                - password
              example:
                id: f626c808-648c-41fe-865d-c6062f3e0899
                name: Secure safebox 01
                password: extremelySecurePassword
      responses:
        '201':
          description: Safebox correctly created
          links:
            open:
              operationId: openSafebox
              parameters:
                path.id: $request.body#/id
              requestBody:
                password: $request.body#/password
            getItems:
              operationId: getSafeboxItems
              parameters:
                path.id: $request.body#/id
            addItem:
              operationId: addSafeboxItem
              parameters:
                path.id: $request.body#/id
        '409':
          description: Safebox already exists
        '422':
          description: Malformed expected data
        '500':
          description: Unexpected API error

  /safeboxes/{id}/open:
    get:
      summary: Open a safebox
      operationId: openSafebox
      description: |
        Opens the safebox identified by the given ID and password.
      parameters:
        - in: path
          name: id
          description: Safebox ID
          required: true
          schema:
            type: string
        - in: header
          name: X-SafeIsh-Password
          description: base64-encoded safebox password (only use along with other security mechanism such as HTTPS/SSL)
          required: true
          schema:
            type: string
          example: ZXh0cmVtZWx5U2VjdXJlUGFzc3dvcmQ=
      responses:
        '200':
          description: Safebox correctly opened
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    description: Token for future actions over an opening safebox
                    type: string
                required:
                  - id
                example:
                  token: RkbfZSW5MmcK3b7kcgg
          links:
            getItems:
              operationId: getSafeboxItems
              parameters:
                path.id: $request.body#/id
                header.X-SafeIsh-Token: $response.body#/token
            addItem:
              operationId: addSafeboxItem
              parameters:
                path.id: $request.body#/id
                header.X-SafeIsh-Token: $response.body#/token
        '404':
          description: Requested safebox does not exist
        '422':
          description: Malformed expected data
        '423':
          description: Requested safebox is locked
        '500':
          description: Unexpected API error

  /safeboxes/{id}/items:
    get:
      summary: Retrieves the content of a safebox
      operationId: getSafeboxItems
      description:
        Retrieves the currently stored contents in the safebox identified by the given ID and with the given opening token.
      security:
        - bearerToken: [ ]
      parameters:
        - in: path
          name: id
          description: Safebox Id
          required: true
          schema:
            type: string
        - in: header
          name: X-SafeIsh-Token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Safebox contents correctly retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    description: Safebox items
                    type: array
                    items:
                      type: string
                required:
                  - items
                example:
                  items:
                    - Safebox content 03
                    - Safebox content 02
                    - Safebox content 01
          links:
            addItem:
              operationId: addSafeboxItem
              parameters:
                path.id: $request.body#/id
                header.X-SafeIsh-Token: $request.header.X-SafeIsh-Token
        '401':
          description: Specified token does not match
        '404':
          description: Requested safebox does not exist
        '422':
          description: Malformed expected data
        '423':
          description: Requested safebox is locked
        '500':
          description: Unexpected API error

    put:
      summary: Add an item to a Safebox
      operationId: addSafeboxItem
      description: |
        Inserts new contents in the safebox identified by the given ID and with the given opening token.
      security:
        - bearerToken: [ ]
      parameters:
        - in: path
          name: id
          description: Safebox ID
          required: true
          schema:
            type: string
        - in: header
          name: X-SafeIsh-Token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  description: Safebox items
                  type: array
                  items:
                    type: string
              required:
                - items
              example:
                items:
                  - Safebox content 03
                  - Safebox content 02
                  - Safebox content 01
                  - New safebox content
      responses:
        '200':
          description: Content correctly added to the safebox
          links:
            getItems:
              operationId: getSafeboxItems
              parameters:
                path.id: $request.body#/id
                header.X-SafeIsh-Token: $request.header.X-SafeIsh-Token
        '401':
          description: Specified token does not match
        '404':
          description: Requested safebox does not exist
        '422':
          description: Malformed expected data
        '423':
          description: Requested safebox is locked
        '500':
          description: Unexpected API error

components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
