---
openapi: 3.0.1
info:
  description: SafeIsh API - The most secure safebox
  version: 1.0.0
  title: SafeIsh API
paths:
  "/api/v1/safeboxes":
    post:
      summary: Creates a safebox
      tags:
      - Safeboxes
      operationId: createSafebox
      description: Creates a new safebox based on a UUID, a non-empty name and a password.
      parameters: []
      responses:
        '201':
          description: Safebox successfully created
          links:
            open:
              operationId: openSafebox
              parameters:
                path.id: "$request.body#/data/id"
                header.X-SafeIsh-Password: "$request.body#/data/attributes/password"
            getItems:
              operationId: getSafeboxItems
              parameters:
                path.id: "$request.body#/data/id"
            addItem:
              operationId: addSafeboxItem
              parameters:
                path.id: "$request.body#/data/id"
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/safebox"
        '406':
          description: Not acceptable media type
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '409':
          description: Safebox already exists
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '415':
          description: Unsupported media type
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '422':
          description: Malformed expected data
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '500':
          description: Unexpected API error
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/new_safebox"
  "/api/v1/safeboxes/{id}/items":
    get:
      summary: Retrieves the content of a safebox
      tags:
      - Safeboxes
      operationId: getSafeboxItems
      description: Retrieves the currently stored contents in the safebox identified
        by the given ID and opening token.
      parameters:
      - name: id
        in: path
        schema:
          type: string
        description: Safebox ID
        required: true
        example: f626c808-648c-41fe-865d-c6062f3e0899
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Safebox contents successfully retrieved
          links:
            addItem:
              operationId: addSafeboxItem
              parameters:
                path.id: "$request.path#/id"
                header.Authorization: "$request.header.Authorization"
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/safebox_items"
        '401':
          description: Invalid token provided to retrieve safebox items
          headers:
            WWW-Authenticate:
              schema:
                type: string
                description: Indicates what authentication schemes can be used to
                  access the resource.
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '404':
          description: Safebox not found
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '406':
          description: Not acceptable media type
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '415':
          description: Unsupported media type
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '423':
          description: Safebox is locked
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '500':
          description: Unexpected API error
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
  "/api/v1/safeboxes/{id}/open":
    post:
      summary: Opens a safebox
      tags:
      - Safeboxes
      operationId: openSafebox
      description: Opens the safebox identified by the given ID and password.
      parameters:
      - name: id
        in: path
        schema:
          type: string
        description: Safebox ID
        required: true
        example: f626c808-648c-41fe-865d-c6062f3e0899
      - name: X-SafeIsh-Password
        in: header
        schema:
          type: string
        description: Base64-encoded safebox password (use with another security mechanism
          such as HTTPS/SSL)
        required: true
        example: ZXh0cmVtZWx5U2VjdXJlUGFzc3dvcmQ=
      responses:
        '200':
          description: Safebox successfully opened
          links:
            getItems:
              operationId: getSafeboxItems
              parameters:
                path.id: "$request.path#/id"
                header.Authorization: "$response.body#/data/id"
            addItem:
              operationId: addSafeboxItem
              parameters:
                path.id: "$request.path#/id"
                header.Authorization: "$response.body#/data/id"
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/safebox_token"
        '401':
          description: Invalid password provided to open safebox
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '404':
          description: Safebox not found
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '406':
          description: Not acceptable media type
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '415':
          description: Unsupported media type
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '423':
          description: Safebox is locked
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
        '500':
          description: Unexpected API error
          content:
            application/vnd.api+json:
              schema:
                "$ref": "#/components/schemas/api_error"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    new_safebox:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: f626c808-648c-41fe-865d-c6062f3e0899
              pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
            type:
              type: string
              example: safebox
            attributes:
              type: object
              properties:
                name:
                  type: string
                  example: Secure safebox 01
                  minLength: 3
                  maxLength: 50
                password:
                  type: string
                  example: extremelySecurePassword
                  minLength: 6
              required:
              - name
              - password
          required:
          - id
          - type
          - attributes
      required:
      - data
    safebox:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: f626c808-648c-41fe-865d-c6062f3e0899
            type:
              type: string
              example: safebox
            attributes:
              type: object
              properties:
                name:
                  type: string
                  example: Secure safebox 01
              required:
              - name
          required:
          - id
          - type
          - attributes
      required:
      - data
    safebox_token:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              example: eyJfcmFpbHMiOnsiZGF0YSI6WyJjZDcyMjY4OS1hYThiLTQ0NDctOWZkZi1mMTQ3N2MwMDE2YmMiXSwiZXhwIjoiMjAyNC0wMy0wNlQxMDo1ODoyNS42OTFaIiwicHVyIjoiU2FmZWJveGVzOjpTYWZlYm94ZXM6OkluZnJhc3RydWN0dXJlOjpTYWZlYm94UmVjb3JkXG5vcGVuXG4xODAifX0=--7af9de4900d56ac3b2c80468e0343db9ba101bef
            type:
              type: string
              example: safeboxToken
          required:
          - id
          - type
      required:
      - data
    safebox_items:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                example: f626c808-648c-41fe-865d-c6062f3e0899
              type:
                type: string
                example: safeboxItem
              attributes:
                type: object
                properties:
                  name:
                    type: string
                    example: Safebox content 01
                required:
                - name
              relationships:
                type: object
                properties:
                  safebox:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id:
                            type: string
                            format: uuid
                            example: f1e0ca7c-4972-4383-a538-cd6ad52aa08f
                          type:
                            type: string
                            example: safebox
                        required:
                        - id
                        - type
                    required:
                    - data
                required:
                - safebox
            required:
            - id
            - type
            - attributes
            - relationships
      required:
      - data
    api_error:
      type: object
      properties:
        errors:
          type: array
          items:
            properties:
              id:
                type: string
                format: uuid
                example: 9a80bb9b-3e9c-4eef-83b6-12990cf0aab2
              title:
                type: string
                example: Unknown attribute
              detail:
                type: string
                example: 'Unknown attribute: ''userId'''
              status:
                type: string
                example: '400'
              code:
                type: string
                example: '101'
              source:
                type: object
                properties:
                  pointer:
                    type: string
                    example: data/attributes/userId
                  parameter:
                    type: string
                    example: filter[invalidField]
                  header:
                    type: string
                    example: Content-Type
              meta:
                type: object
            required:
            - title
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
